# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_auto_20160621_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='LinksBetweenEntities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unmarked', models.BooleanField(default=0)),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_entity', to='entity.Entity')),
                ('to_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_entity', to='entity.Entity')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='links',
            field=models.ManyToManyField(through='entity.LinksBetweenEntities', to='entity.Entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
